spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pre_project?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret: mySecretKey  # JWT 시크릿 키
      expiration: 3600000  # 토큰 유효 시간 (밀리초)
      token-prefix: Bearer  # 토큰 프리픽스
      header: Authorization  # 헤더 이름