spring:
  datasource:
    url: jdbc:mysql://prepro.cj9ox8a3bt5e.ap-northeast-2.rds.amazonaws.com:3306/pre_project?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 160218!!
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    security:
      jwt:
        secret: mySecretKey  # JWT 시크릿 키
        expiration: 3600000  # 토큰 유효 시간 (밀리초)
        token-prefix: Bearer  # 토큰 프리픽스
        header: Authorization  # 헤더 이름